Database retries and timeouts
discordapp/incubator-airflow pull request #3
Opened 2019-03-27 19:08 UTC by spennihana

2019-03-27 19:33 UTC, jingsong approved these changes
shipit. i need moar sleep.

2019-03-29 17:50 UTC, jingsong approved these changes
beboop beboop

2019-03-29 21:32 UTC, samschlegel approved these changes

2019-03-29 21:32 UTC, samschlegel commented on airflow/settings.py
> +    connect_args['connect_timeout'] = connect_timeout_seconds
Do we know if this works for all databases that are currently supported (SQLite, MySQL, Postgres)

2019-03-29 21:32 UTC, samschlegel commented on airflow/settings.py
> +    connect_args['options'] = '-c statement_timeout={}'.format(statement_timeout_seconds * 1000)
This only works when Postgres is the backend. MySQL has a different thing iirc, and SQLite doesn't really have connections. Can just gate this to Postgres only for now probably, with a note that support should be added for MySQL

2019-03-29 21:33 UTC, samschlegel requested changes
oops meant to request changes

2019-03-29 21:34 UTC, samschlegel commented on airflow/config_templates/default_airflow.cfg
> +sql_alchemy_statement_max_retries = 10
These configs should be moved to the retrying PR

2019-03-29 21:35 UTC, samschlegel commented on airflow/config_templates/default_airflow.cfg
> +sql_alchemy_statement_timeout_seconds = 30
Both of these timeouts should default to 0 which would disable. Enabling this by default could be very surprising and potentially break things

2019-04-01 21:24 UTC, samschlegel commented
Do you know if setting them to 0 will actually disable on the SQLAlchemy side? Or do we need to just remove the flag when it's 0

2023-08-29 14:34 UTC, closed without merging